[2024-11-11T18:47:57.756+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T18:47:57.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_pipeline.Best_Model manual__2024-11-11T18:46:32.526075+00:00 [queued]>
[2024-11-11T18:47:57.780+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_pipeline.Best_Model manual__2024-11-11T18:46:32.526075+00:00 [queued]>
[2024-11-11T18:47:57.780+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-11T18:47:57.787+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Best_Model> on 2024-11-11 18:46:32.526075+00:00
[2024-11-11T18:47:57.796+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-11T18:47:57.798+0000] {standard_task_runner.py:63} INFO - Started process 255 to run task
[2024-11-11T18:47:57.798+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'modeling_pipeline', 'Best_Model', 'manual__2024-11-11T18:46:32.526075+00:00', '--job-id', '928', '--raw', '--subdir', 'DAGS_FOLDER/dag_script_model.py', '--cfg-path', '/tmp/tmpw4a14n_b']
[2024-11-11T18:47:57.800+0000] {standard_task_runner.py:91} INFO - Job 928: Subtask Best_Model
[2024-11-11T18:47:57.824+0000] {task_command.py:426} INFO - Running <TaskInstance: modeling_pipeline.Best_Model manual__2024-11-11T18:46:32.526075+00:00 [running]> on host 5039cd089413
[2024-11-11T18:47:57.890+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='modeling_pipeline' AIRFLOW_CTX_TASK_ID='Best_Model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T18:46:32.526075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T18:46:32.526075+00:00'
[2024-11-11T18:47:57.891+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T18:47:57.924+0000] {logging_mixin.py:188} INFO - 228524954728212615
[2024-11-11T18:47:57.994+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T18:47:57.996+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bestmodel.py", line 76, in main
    model, best_rmse, best_experiment_name, best_run_id = get_best_model_and_load_weights(experiment_names)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bestmodel.py", line 50, in get_best_model_and_load_weights
    model = mlflow.sklearn.load_model(best_model_uri)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/sklearn/__init__.py", line 634, in load_model
    flavor_conf = _get_flavor_configuration(model_path=local_model_path, flavor_name=FLAVOR_NAME)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/model_utils.py", line 61, in _get_flavor_configuration
    return Model.load(model_path).flavors[flavor_name]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/models/model.py", line 657, in load
    return cls.from_dict(yaml.safe_load(f.read()))
                                        ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
[2024-11-11T18:47:58.006+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=modeling_pipeline, task_id=Best_Model, run_id=manual__2024-11-11T18:46:32.526075+00:00, execution_date=20241111T184632, start_date=20241111T184757, end_date=20241111T184758
[2024-11-11T18:47:58.013+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 928 for task Best_Model ('utf-8' codec can't decode byte 0x80 in position 0: invalid start byte; 255)
[2024-11-11T18:47:58.022+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-11T18:47:58.034+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T18:47:58.035+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
