[2024-10-31T04:07:01.893+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:01.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:07:01.896+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:01.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:06.586+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:07.102+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:07.083+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:07:07.153+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:07.153+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:07:07.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 5.353 seconds
[2024-10-31T04:07:37.473+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:37.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:07:37.480+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:37.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:39.200+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:39.327+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:39.326+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:07:39.334+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:39.334+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:07:39.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.888 seconds
[2024-10-31T04:08:09.677+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:09.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:08:09.685+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:09.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:10.990+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:11.010+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:11.010+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:08:11.018+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:11.018+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:08:11.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.362 seconds
[2024-10-31T04:08:41.311+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:41.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:08:41.330+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:41.328+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:42.131+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:42.147+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:42.146+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:08:42.151+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:42.151+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:08:42.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.860 seconds
[2024-10-31T04:31:47.781+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:31:47.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:31:47.790+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:31:47.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:31:51.792+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:31:51.790+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:31:51.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:31:51.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 4.056 seconds
[2024-10-31T04:32:22.167+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:22.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:32:22.170+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:22.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:23.098+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:23.097+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:32:23.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:23.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.946 seconds
[2024-10-31T04:32:53.442+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:53.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:32:53.444+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:53.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:54.480+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:54.479+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:32:54.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:54.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.062 seconds
[2024-10-31T04:33:24.749+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:33:24.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:33:24.753+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:33:24.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:33:25.603+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:33:25.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:33:25.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:33:25.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.871 seconds
[2024-10-31T04:37:57.393+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:37:57.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:37:57.400+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:37:57.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:37:59.426+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:37:59.425+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T04:38:00.092+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:38:00.087+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:38:00.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:00.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.843 seconds
[2024-10-31T04:38:22.430+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:22.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:38:22.435+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:38:22.434+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:23.378+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:38:23.377+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:38:23.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:23.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.967 seconds
[2024-10-31T04:39:04.227+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:04.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:39:04.234+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:04.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:06.018+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:06.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:39:06.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:06.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.845 seconds
[2024-10-31T04:39:36.348+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:36.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:39:36.352+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:36.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:37.354+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:37.353+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:39:37.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:37.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.028 seconds
[2024-10-31T04:40:07.621+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:07.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:40:07.627+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:07.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:08.620+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:08.619+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:40:08.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:08.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.031 seconds
[2024-10-31T04:40:39.015+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:39.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:40:39.033+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:39.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:40.288+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:40.287+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:40:40.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:40.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.311 seconds
[2024-10-31T04:41:10.614+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:10.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:41:10.620+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:10.620+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:11.490+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:11.488+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:41:11.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:11.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.897 seconds
[2024-10-31T04:41:41.613+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:41.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:41:41.618+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:41.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:42.382+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:42.380+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:41:42.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:42.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.786 seconds
[2024-10-31T04:46:14.175+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:14.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:46:14.186+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:14.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:15.959+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:15.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:46:15.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:15.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.830 seconds
[2024-10-31T04:46:46.327+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:46.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:46:46.331+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:46.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:47.385+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:47.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:46:47.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:47.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.086 seconds
[2024-10-31T04:49:14.069+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:14.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:49:14.084+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:14.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:15.912+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:15.909+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:49:15.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:15.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.897 seconds
[2024-10-31T04:49:46.492+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:46.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:49:46.510+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:46.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:48.792+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:48.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:49:48.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:48.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.381 seconds
[2024-10-31T04:50:19.105+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:19.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:50:19.127+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:19.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:20.145+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:20.143+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:50:20.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:20.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.068 seconds
[2024-10-31T04:50:50.393+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:50.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:50:50.402+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:50.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:51.315+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:51.313+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:50:51.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:51.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.951 seconds
[2024-10-31T04:51:21.742+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:51:21.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:51:21.749+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:51:21.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:51:22.763+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:51:22.762+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:51:22.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:51:22.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.041 seconds
[2024-10-31T04:55:51.495+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:55:51.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:55:51.501+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:55:51.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:56:21.000+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:56:20.993+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T04:56:21.505+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:56:21.501+0000] {timeout.py:68} ERROR - Process timed out, PID: 130
[2024-10-31T05:02:13.306+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:13.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:02:13.312+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:13.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:24.541+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:24.540+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:02:28.045+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:28.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:02:28.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:28.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 14.834 seconds
[2024-10-31T05:02:59.609+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:59.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:02:59.757+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:59.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:03:12.264+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:03:12.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:03:12.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:03:12.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 12.933 seconds
[2024-10-31T05:03:43.659+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:03:43.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:03:43.822+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:03:43.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:04.884+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:04.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:12:04.945+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:04.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:11.328+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:11.326+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:12:12.097+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:12.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:12:12.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:12.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 7.406 seconds
[2024-10-31T05:12:42.762+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:42.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:12:42.817+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:42.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:44.804+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:44.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:12:44.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:44.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.172 seconds
[2024-10-31T05:13:14.947+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:14.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:13:14.954+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:14.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:16.056+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:16.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:13:16.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:16.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.146 seconds
[2024-10-31T05:13:46.346+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:46.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:13:46.355+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:46.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:47.283+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:47.282+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:13:47.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:47.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.059 seconds
[2024-10-31T05:23:47.803+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:23:47.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:23:47.815+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:23:47.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:23:50.729+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:23:50.727+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:23:51.483+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:23:51.480+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:23:51.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:23:51.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 3.723 seconds
[2024-10-31T05:24:21.853+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:21.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:24:21.860+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:21.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:23.577+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:23.575+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:24:23.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:23.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.753 seconds
[2024-10-31T05:24:53.963+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:53.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:24:53.967+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:53.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:55.182+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:55.181+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:24:55.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:55.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.253 seconds
[2024-10-31T05:25:25.934+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:25:26.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:25:26.120+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:25:26.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:25:29.653+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:25:29.650+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:25:29.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:25:29.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 3.927 seconds
[2024-10-31T05:26:00.377+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:26:00.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:26:00.383+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:26:00.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:26:01.415+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:26:01.413+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:26:01.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:26:01.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.096 seconds
[2024-10-31T05:34:05.581+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:05.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:34:05.586+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:05.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:13.364+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:13.361+0000] {font_manager.py:1547} INFO - generated new fontManager
[2024-10-31T05:34:15.292+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:15.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:34:15.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:15.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 9.995 seconds
[2024-10-31T05:34:46.227+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:46.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:34:46.301+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:46.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:52.861+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:52.853+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:34:52.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:52.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 6.758 seconds
[2024-10-31T05:35:23.423+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:23.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:35:23.428+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:23.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:24.399+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:24.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:35:24.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:24.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.003 seconds
[2024-10-31T05:35:54.933+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:54.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:35:54.943+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:54.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:55.776+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:55.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:35:55.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:55.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.902 seconds
[2024-10-31T05:59:10.712+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:10.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:59:10.715+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:10.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:12.105+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:12.105+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:59:12.413+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:12.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:59:12.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:12.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.731 seconds
[2024-10-31T05:59:42.725+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:42.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:59:42.728+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:42.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:43.522+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:43.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:59:43.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:43.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.827 seconds
[2024-10-31T06:00:13.873+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:13.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:00:13.878+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:13.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:14.732+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:14.731+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:00:14.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:14.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.881 seconds
[2024-10-31T06:00:45.046+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:45.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:00:45.050+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:45.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:45.764+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:45.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:00:45.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:45.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.739 seconds
[2024-10-31T06:02:04.520+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:04.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:02:04.526+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:04.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:06.942+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:06.940+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T06:02:07.616+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:07.614+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:02:07.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:07.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 3.130 seconds
[2024-10-31T06:02:37.888+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:37.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:02:37.900+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:37.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:39.406+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:39.405+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:02:39.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:39.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.609 seconds
[2024-10-31T06:03:09.860+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:09.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:03:09.867+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:09.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:11.238+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:11.237+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:03:11.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:11.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.426 seconds
[2024-10-31T06:03:41.609+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:41.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:03:41.615+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:41.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:42.395+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:42.394+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:03:42.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:42.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.806 seconds
[2024-10-31T06:04:12.769+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:12.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:04:12.773+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:12.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:13.663+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:13.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:04:13.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:13.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.919 seconds
[2024-10-31T06:04:44.042+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:44.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:04:44.070+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:44.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:44.919+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:44.918+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:04:44.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:44.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.910 seconds
[2024-10-31T06:05:15.359+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:15.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:05:15.364+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:15.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:16.255+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:16.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:05:16.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:16.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.926 seconds
[2024-10-31T06:05:46.663+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:46.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:05:46.674+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:46.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:47.593+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:47.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:05:47.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:47.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.956 seconds
[2024-10-31T15:42:56.323+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:42:56.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:42:56.326+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:42:56.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:42:57.962+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:42:57.962+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T15:42:58.318+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:42:58.317+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 26, in <module>
    from dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema import main_train_schema
ImportError: cannot import name 'main_train_schema' from 'dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema' (/opt/airflow/dags/DataPreprocessing/src/Schema/train_schema/check_output_data_schema.py)
[2024-10-31T15:42:58.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:42:58.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.014 seconds
[2024-10-31T15:43:28.589+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:43:28.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:43:28.600+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:43:28.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:43:29.384+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:43:29.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 26, in <module>
    from dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema import main_train_schema
ImportError: cannot import name 'main_train_schema' from 'dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema' (/opt/airflow/dags/DataPreprocessing/src/Schema/train_schema/check_output_data_schema.py)
[2024-10-31T15:43:29.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:43:29.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.830 seconds
[2024-10-31T15:43:59.673+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:43:59.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:43:59.677+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:43:59.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:44:00.496+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:44:00.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 26, in <module>
    from dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema import main_train_schema
ImportError: cannot import name 'main_train_schema' from 'dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema' (/opt/airflow/dags/DataPreprocessing/src/Schema/train_schema/check_output_data_schema.py)
[2024-10-31T15:44:00.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:44:00.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.847 seconds
[2024-10-31T15:44:30.821+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:44:30.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:44:30.824+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:44:30.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:44:31.591+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:44:31.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 26, in <module>
    from dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema import main_train_schema
ImportError: cannot import name 'main_train_schema' from 'dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema' (/opt/airflow/dags/DataPreprocessing/src/Schema/train_schema/check_output_data_schema.py)
[2024-10-31T15:44:31.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:44:31.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.788 seconds
[2024-10-31T15:45:01.904+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:45:01.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:45:01.909+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:45:01.909+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:45:02.606+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:45:02.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 26, in <module>
    from dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema import main_train_schema
ImportError: cannot import name 'main_train_schema' from 'dags.DataPreprocessing.src.Schema.train_schema.check_output_data_schema' (/opt/airflow/dags/DataPreprocessing/src/Schema/train_schema/check_output_data_schema.py)
[2024-10-31T15:45:02.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:45:02.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.718 seconds
[2024-10-31T15:45:51.706+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:45:51.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:45:51.711+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:45:51.710+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:45:53.769+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:45:53.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:45:53.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:45:53.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.123 seconds
[2024-10-31T15:46:24.086+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:46:24.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:46:24.090+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:46:24.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:46:24.859+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:46:24.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:46:24.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:46:24.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.788 seconds
[2024-10-31T15:46:34.985+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:46:34.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:46:34.989+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:46:34.988+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:46:35.728+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:46:35.727+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:46:35.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:46:35.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.767 seconds
[2024-10-31T15:47:06.026+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:47:06.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:47:06.031+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:47:06.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:47:06.767+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:47:06.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:47:06.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:47:06.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.757 seconds
[2024-10-31T15:47:37.031+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:47:37.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:47:37.035+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:47:37.034+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:47:37.795+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:47:37.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:47:37.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:47:37.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.781 seconds
[2024-10-31T15:48:07.947+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:48:07.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:48:07.952+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:48:07.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:48:08.733+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:48:08.733+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:48:08.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:48:08.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.806 seconds
[2024-10-31T15:48:39.051+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:48:39.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:48:39.056+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:48:39.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:48:39.792+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:48:39.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:48:39.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:48:39.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.759 seconds
[2024-10-31T15:49:10.069+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:10.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:49:10.075+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:49:10.075+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:10.803+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:49:10.803+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:49:10.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:10.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.752 seconds
[2024-10-31T15:49:41.094+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:41.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:49:41.100+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:49:41.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:41.813+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:49:41.812+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:49:41.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:41.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.734 seconds
[2024-10-31T15:49:49.757+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:49.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:49:49.760+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:49:49.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:50.379+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:49:50.378+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:49:50.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:49:50.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.637 seconds
[2024-10-31T15:50:56.724+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:50:56.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:50:56.728+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:50:56.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:50:58.214+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:50:58.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:50:58.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:50:58.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.514 seconds
[2024-10-31T15:51:28.549+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:51:28.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:51:28.553+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:51:28.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:51:29.301+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:51:29.300+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 68, in <module>
    data_schema_original = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:51:29.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:51:29.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.768 seconds
[2024-10-31T15:51:50.530+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:51:50.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:51:50.534+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:51:50.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:51:51.285+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:51:51.284+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 137, in <module>
    data_schema_train_data_feature_eng = PythonOperator(
                                         ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-10-31T15:51:51.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:51:51.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.791 seconds
[2024-10-31T15:52:01.231+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:52:01.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:52:01.234+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:52:01.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:52:02.116+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:52:02.243+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:52:02.242+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:52:02.247+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:52:02.247+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:52:02.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.033 seconds
[2024-10-31T15:52:34.533+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:52:34.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:52:34.542+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:52:34.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:52:36.196+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:52:36.366+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:52:36.365+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:52:36.374+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:52:36.374+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:52:36.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.874 seconds
[2024-10-31T15:53:06.734+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:53:06.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:53:06.739+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:53:06.738+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:53:07.547+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:53:07.561+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:53:07.561+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:53:07.566+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:53:07.566+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:53:07.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.857 seconds
[2024-10-31T15:53:37.911+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:53:37.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:53:37.915+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:53:37.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:53:38.649+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:53:38.664+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:53:38.663+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:53:38.668+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:53:38.668+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:53:38.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.773 seconds
[2024-10-31T15:54:08.979+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:54:08.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:54:08.991+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:54:08.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:54:09.786+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:54:09.808+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:54:09.807+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:54:09.821+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:54:09.821+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:54:09.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.868 seconds
[2024-10-31T15:54:40.131+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:54:40.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:54:40.136+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:54:40.136+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:54:40.926+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:54:40.940+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:54:40.940+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:54:40.946+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:54:40.946+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:54:40.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.831 seconds
[2024-10-31T15:55:11.236+0000] {processor.py:161} INFO - Started process (PID=133) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:55:11.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:55:11.241+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:55:11.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:55:12.082+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:55:12.093+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:55:12.093+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:55:12.098+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:55:12.098+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:55:12.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.877 seconds
[2024-10-31T15:55:42.377+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:55:42.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:55:42.382+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:55:42.381+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:55:43.111+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:55:43.123+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:55:43.123+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:55:43.128+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:55:43.128+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:55:43.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.765 seconds
[2024-10-31T15:56:13.407+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:56:13.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:56:13.412+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:56:13.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:56:14.138+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:56:14.150+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:56:14.150+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:56:14.155+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:56:14.154+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:56:14.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.763 seconds
[2024-10-31T15:56:44.464+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:56:44.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:56:44.469+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:56:44.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:56:45.235+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:56:45.249+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:56:45.249+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:56:45.255+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:56:45.255+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:56:45.268+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.811 seconds
[2024-10-31T15:57:15.571+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:57:15.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:57:15.575+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:57:15.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:57:16.406+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:57:16.420+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:57:16.420+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:57:16.425+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:57:16.425+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:57:16.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.869 seconds
[2024-10-31T15:57:46.792+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:57:46.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:57:46.797+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:57:46.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:57:47.557+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:57:47.569+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:57:47.569+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:57:47.574+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:57:47.574+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:57:47.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.797 seconds
[2024-10-31T15:58:17.860+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:58:17.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:58:17.864+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:58:17.864+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:58:18.627+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:58:18.643+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:58:18.643+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:58:18.648+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:58:18.648+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:58:18.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.803 seconds
[2024-10-31T15:58:48.922+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:58:48.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:58:48.926+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:58:48.925+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:58:49.617+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:58:49.629+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:58:49.629+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:58:49.634+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:58:49.634+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:58:49.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.723 seconds
[2024-10-31T15:59:19.894+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:59:19.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:59:19.897+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:59:19.897+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:59:20.676+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:59:20.689+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:59:20.689+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:59:20.693+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:59:20.693+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:59:20.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.809 seconds
[2024-10-31T15:59:50.771+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T15:59:50.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T15:59:50.773+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:59:50.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T15:59:51.635+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T15:59:51.646+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:59:51.646+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T15:59:51.650+0000] {logging_mixin.py:188} INFO - [2024-10-31T15:59:51.650+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T15:59:51.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.888 seconds
[2024-10-31T16:00:21.911+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:00:21.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:00:21.914+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:00:21.913+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:00:22.733+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:00:22.749+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:00:22.749+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:00:22.755+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:00:22.755+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:00:22.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.855 seconds
[2024-10-31T16:01:50.850+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:01:50.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:01:50.860+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:01:50.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:01:52.525+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:01:52.611+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:01:52.610+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:01:52.616+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:01:52.616+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:01:52.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.780 seconds
[2024-10-31T16:02:22.901+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:02:22.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:02:22.905+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:02:22.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:02:23.752+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:02:23.769+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:02:23.769+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:02:23.774+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:02:23.774+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:02:23.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.886 seconds
[2024-10-31T16:02:54.055+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:02:54.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:02:54.059+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:02:54.059+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:02:54.839+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:02:54.855+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:02:54.855+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:02:54.860+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:02:54.860+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:02:54.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.819 seconds
[2024-10-31T16:03:25.139+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:03:25.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:03:25.144+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:03:25.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:03:26.048+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:03:26.065+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:03:26.065+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:03:26.070+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:03:26.070+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:03:26.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.946 seconds
[2024-10-31T16:03:56.381+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:03:56.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:03:56.386+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:03:56.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:03:57.234+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:03:57.247+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:03:57.246+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:03:57.252+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:03:57.252+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:03:57.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.884 seconds
[2024-10-31T16:04:27.511+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:04:27.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:04:27.515+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:04:27.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:04:28.356+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:04:28.371+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:04:28.370+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:04:28.376+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:04:28.376+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:04:28.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.878 seconds
[2024-10-31T16:04:58.645+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:04:58.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:04:58.649+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:04:58.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:04:59.405+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:04:59.419+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:04:59.419+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:04:59.424+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:04:59.424+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:04:59.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.791 seconds
[2024-10-31T16:05:29.661+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:05:29.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:05:29.665+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:05:29.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:05:30.420+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:05:30.433+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:05:30.433+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:05:30.438+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:05:30.437+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:05:30.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.791 seconds
[2024-10-31T16:06:00.626+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:06:00.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:06:00.630+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:06:00.629+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:06:01.414+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:06:01.426+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:06:01.426+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:06:01.431+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:06:01.431+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:06:01.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.819 seconds
[2024-10-31T16:06:31.735+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:06:31.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:06:31.740+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:06:31.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:06:32.525+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:06:32.539+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:06:32.539+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:06:32.543+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:06:32.543+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:06:32.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.824 seconds
[2024-10-31T16:07:02.900+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:07:02.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:07:02.904+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:07:02.903+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:07:03.697+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:07:03.710+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:07:03.710+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:07:03.715+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:07:03.715+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:07:03.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.828 seconds
[2024-10-31T16:07:34.006+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:07:34.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:07:34.010+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:07:34.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:07:34.885+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:07:34.899+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:07:34.899+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:07:34.903+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:07:34.903+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:07:34.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.910 seconds
[2024-10-31T16:08:05.177+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:08:05.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:08:05.181+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:08:05.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:08:06.109+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:08:06.124+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:08:06.124+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:08:06.129+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:08:06.129+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:08:06.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.969 seconds
[2024-10-31T16:08:54.602+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:08:54.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:08:54.607+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:08:54.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:08:56.557+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:08:56.737+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:08:56.736+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:08:56.752+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:08:56.751+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:08:56.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.190 seconds
[2024-10-31T16:09:26.933+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:09:26.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:09:26.937+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:09:26.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:09:28.225+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:09:28.243+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:09:28.243+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:09:28.253+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:09:28.253+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:09:28.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.346 seconds
[2024-10-31T16:09:58.491+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:09:58.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:09:58.498+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:09:58.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:09:59.586+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:09:59.608+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:09:59.608+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:09:59.613+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:09:59.613+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:09:59.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.150 seconds
[2024-10-31T16:10:29.816+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:10:29.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:10:29.820+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:10:29.819+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:10:30.980+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:10:31.002+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:10:31.002+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:10:31.009+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:10:31.009+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:10:31.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.215 seconds
[2024-10-31T16:11:01.136+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:11:01.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:11:01.140+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:11:01.139+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:11:01.853+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:11:01.884+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:11:01.884+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:11:01.891+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:11:01.891+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:11:01.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.769 seconds
[2024-10-31T16:11:32.176+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T16:11:32.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T16:11:32.181+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:11:32.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T16:11:32.920+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T16:11:32.935+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:11:32.935+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T16:11:32.942+0000] {logging_mixin.py:188} INFO - [2024-10-31T16:11:32.942+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T16:11:32.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.782 seconds
