[2024-10-31T04:07:01.893+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:01.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:07:01.896+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:01.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:06.586+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:07.102+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:07.083+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:07:07.153+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:07.153+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:07:07.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 5.353 seconds
[2024-10-31T04:07:37.473+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:37.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:07:37.480+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:37.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:39.200+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:07:39.327+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:39.326+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:07:39.334+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:07:39.334+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:07:39.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.888 seconds
[2024-10-31T04:08:09.677+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:09.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:08:09.685+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:09.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:10.990+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:11.010+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:11.010+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:08:11.018+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:11.018+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:08:11.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.362 seconds
[2024-10-31T04:08:41.311+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:41.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:08:41.330+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:41.328+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:42.131+0000] {processor.py:840} INFO - DAG(s) 'datapipeline_new' retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:08:42.147+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:42.146+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-31T04:08:42.151+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:08:42.151+0000] {dag.py:3954} INFO - Setting next_dagrun for datapipeline_new to None, run_after=None
[2024-10-31T04:08:42.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.860 seconds
[2024-10-31T04:31:47.781+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:31:47.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:31:47.790+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:31:47.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:31:51.792+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:31:51.790+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:31:51.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:31:51.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 4.056 seconds
[2024-10-31T04:32:22.167+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:22.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:32:22.170+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:22.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:23.098+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:23.097+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:32:23.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:23.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.946 seconds
[2024-10-31T04:32:53.442+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:53.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:32:53.444+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:53.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:54.480+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:32:54.479+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:32:54.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:32:54.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.062 seconds
[2024-10-31T04:33:24.749+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:33:24.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:33:24.753+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:33:24.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:33:25.603+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:33:25.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 6, in <module>
    from ml_metadata.proto import metadata_store_pb2
ModuleNotFoundError: No module named 'ml_metadata'
[2024-10-31T04:33:25.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:33:25.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.871 seconds
[2024-10-31T04:37:57.393+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:37:57.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:37:57.400+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:37:57.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:37:59.426+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:37:59.425+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T04:38:00.092+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:38:00.087+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:38:00.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:00.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.843 seconds
[2024-10-31T04:38:22.430+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:22.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:38:22.435+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:38:22.434+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:23.378+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:38:23.377+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:38:23.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:38:23.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.967 seconds
[2024-10-31T04:39:04.227+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:04.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:39:04.234+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:04.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:06.018+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:06.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:39:06.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:06.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.845 seconds
[2024-10-31T04:39:36.348+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:36.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:39:36.352+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:36.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:37.354+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:39:37.353+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:39:37.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:39:37.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.028 seconds
[2024-10-31T04:40:07.621+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:07.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:40:07.627+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:07.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:08.620+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:08.619+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:40:08.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:08.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.031 seconds
[2024-10-31T04:40:39.015+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:39.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:40:39.033+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:39.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:40.288+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:40:40.287+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:40:40.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:40:40.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.311 seconds
[2024-10-31T04:41:10.614+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:10.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:41:10.620+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:10.620+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:11.490+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:11.488+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:41:11.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:11.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.897 seconds
[2024-10-31T04:41:41.613+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:41.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:41:41.618+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:41.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:42.382+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:41:42.380+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:41:42.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:41:42.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.786 seconds
[2024-10-31T04:46:14.175+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:14.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:46:14.186+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:14.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:15.959+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:15.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:46:15.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:15.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.830 seconds
[2024-10-31T04:46:46.327+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:46.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:46:46.331+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:46.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:47.385+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:46:47.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:46:47.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:46:47.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.086 seconds
[2024-10-31T04:49:14.069+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:14.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:49:14.084+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:14.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:15.912+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:15.909+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:49:15.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:15.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.897 seconds
[2024-10-31T04:49:46.492+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:46.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:49:46.510+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:46.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:48.792+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:49:48.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:49:48.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:49:48.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.381 seconds
[2024-10-31T04:50:19.105+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:19.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:50:19.127+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:19.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:20.145+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:20.143+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:50:20.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:20.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.068 seconds
[2024-10-31T04:50:50.393+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:50.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:50:50.402+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:50.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:51.315+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:50:51.313+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:50:51.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:50:51.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.951 seconds
[2024-10-31T04:51:21.742+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:51:21.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:51:21.749+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:51:21.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:51:22.763+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:51:22.762+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 15, in swig_import_helper
    import imp
ModuleNotFoundError: No module named 'imp'
[2024-10-31T04:51:22.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T04:51:22.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.041 seconds
[2024-10-31T04:55:51.495+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T04:55:51.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T04:55:51.501+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:55:51.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T04:56:21.000+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:56:20.993+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T04:56:21.505+0000] {logging_mixin.py:188} INFO - [2024-10-31T04:56:21.501+0000] {timeout.py:68} ERROR - Process timed out, PID: 130
[2024-10-31T05:02:13.306+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:13.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:02:13.312+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:13.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:24.541+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:24.540+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:02:28.045+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:28.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:02:28.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:28.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 14.834 seconds
[2024-10-31T05:02:59.609+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:02:59.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:02:59.757+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:02:59.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:03:12.264+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:03:12.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:03:12.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:03:12.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 12.933 seconds
[2024-10-31T05:03:43.659+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:03:43.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:03:43.822+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:03:43.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:04.884+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:04.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:12:04.945+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:04.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:11.328+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:11.326+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:12:12.097+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:12.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:12:12.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:12.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 7.406 seconds
[2024-10-31T05:12:42.762+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:42.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:12:42.817+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:42.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:44.804+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:12:44.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:12:44.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:12:44.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 2.172 seconds
[2024-10-31T05:13:14.947+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:14.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:13:14.954+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:14.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:16.056+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:16.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:13:16.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:16.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.146 seconds
[2024-10-31T05:13:46.346+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:46.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:13:46.355+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:46.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:47.283+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:13:47.282+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:13:47.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:13:47.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.059 seconds
[2024-10-31T05:23:47.803+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:23:47.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:23:47.815+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:23:47.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:23:50.729+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:23:50.727+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:23:51.483+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:23:51.480+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:23:51.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:23:51.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 3.723 seconds
[2024-10-31T05:24:21.853+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:21.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:24:21.860+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:21.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:23.577+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:23.575+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:24:23.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:23.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.753 seconds
[2024-10-31T05:24:53.963+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:53.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:24:53.967+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:53.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:55.182+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:24:55.181+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:24:55.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:24:55.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.253 seconds
[2024-10-31T05:25:25.934+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:25:26.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:25:26.120+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:25:26.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:25:29.653+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:25:29.650+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:25:29.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:25:29.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 3.927 seconds
[2024-10-31T05:26:00.377+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:26:00.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:26:00.383+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:26:00.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:26:01.415+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:26:01.413+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:26:01.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:26:01.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.096 seconds
[2024-10-31T05:34:05.581+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:05.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:34:05.586+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:05.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:13.364+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:13.361+0000] {font_manager.py:1547} INFO - generated new fontManager
[2024-10-31T05:34:15.292+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:15.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:34:15.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:15.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 9.995 seconds
[2024-10-31T05:34:46.227+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:46.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:34:46.301+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:46.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:52.861+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:34:52.853+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:34:52.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:34:52.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 6.758 seconds
[2024-10-31T05:35:23.423+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:23.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:35:23.428+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:23.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:24.399+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:24.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:35:24.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:24.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.003 seconds
[2024-10-31T05:35:54.933+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:54.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:35:54.943+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:54.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:55.776+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:35:55.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.8/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:35:55.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:35:55.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.902 seconds
[2024-10-31T05:59:10.712+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:10.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:59:10.715+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:10.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:12.105+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:12.105+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T05:59:12.413+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:12.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:59:12.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:12.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.731 seconds
[2024-10-31T05:59:42.725+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:42.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T05:59:42.728+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:42.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:43.522+0000] {logging_mixin.py:188} INFO - [2024-10-31T05:59:43.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T05:59:43.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T05:59:43.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.827 seconds
[2024-10-31T06:00:13.873+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:13.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:00:13.878+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:13.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:14.732+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:14.731+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:00:14.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:14.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.881 seconds
[2024-10-31T06:00:45.046+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:45.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:00:45.050+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:45.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:45.764+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:00:45.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:00:45.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:00:45.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.739 seconds
[2024-10-31T06:02:04.520+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:04.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:02:04.526+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:04.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:06.942+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:06.940+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-31T06:02:07.616+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:07.614+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:02:07.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:07.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 3.130 seconds
[2024-10-31T06:02:37.888+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:37.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:02:37.900+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:37.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:39.406+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:02:39.405+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:02:39.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:02:39.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.609 seconds
[2024-10-31T06:03:09.860+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:09.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:03:09.867+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:09.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:11.238+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:11.237+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:03:11.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:11.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 1.426 seconds
[2024-10-31T06:03:41.609+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:41.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:03:41.615+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:41.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:42.395+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:03:42.394+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:03:42.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:03:42.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.806 seconds
[2024-10-31T06:04:12.769+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:12.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:04:12.773+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:12.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:13.663+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:13.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:04:13.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:13.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.919 seconds
[2024-10-31T06:04:44.042+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:44.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:04:44.070+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:44.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:44.919+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:04:44.918+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:04:44.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:04:44.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.910 seconds
[2024-10-31T06:05:15.359+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:15.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:05:15.364+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:15.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:16.255+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:16.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:05:16.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:16.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.926 seconds
[2024-10-31T06:05:46.663+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:46.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_script.py for tasks to queue
[2024-10-31T06:05:46.674+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:46.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:47.593+0000] {logging_mixin.py:188} INFO - [2024-10-31T06:05:47.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_script.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tf_metadata_store_serialized', [dirname(__file__)])
  File "/usr/local/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tf_metadata_store_serialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_script.py", line 24, in <module>
    from dags.DataPreprocessing.src.Schema.check_schema_original_airpollution import  main_check_schema_original
  File "/opt/airflow/dags/DataPreprocessing/src/Schema/check_schema_original_airpollution.py", line 7, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_store.py", line 28, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/home/airflow/.local/lib/python3.9/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 20, in swig_import_helper
    import _pywrap_tf_metadata_store_serialized
ModuleNotFoundError: No module named '_pywrap_tf_metadata_store_serialized'
[2024-10-31T06:05:47.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_script.py
[2024-10-31T06:05:47.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_script.py took 0.956 seconds
