[2024-11-11T01:27:25.363+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T01:27:25.384+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_pipeline.XGBoost_model manual__2024-11-11T01:27:11.105048+00:00 [queued]>
[2024-11-11T01:27:25.416+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_pipeline.XGBoost_model manual__2024-11-11T01:27:11.105048+00:00 [queued]>
[2024-11-11T01:27:25.417+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-11T01:27:25.444+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): XGBoost_model> on 2024-11-11 01:27:11.105048+00:00
[2024-11-11T01:27:25.455+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-11T01:27:25.456+0000] {standard_task_runner.py:63} INFO - Started process 139 to run task
[2024-11-11T01:27:25.457+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'modeling_pipeline', 'XGBoost_model', 'manual__2024-11-11T01:27:11.105048+00:00', '--job-id', '818', '--raw', '--subdir', 'DAGS_FOLDER/dag_script_model.py', '--cfg-path', '/tmp/tmp_07r_8c_']
[2024-11-11T01:27:25.459+0000] {standard_task_runner.py:91} INFO - Job 818: Subtask XGBoost_model
[2024-11-11T01:27:25.507+0000] {task_command.py:426} INFO - Running <TaskInstance: modeling_pipeline.XGBoost_model manual__2024-11-11T01:27:11.105048+00:00 [running]> on host 7e55f590dc51
[2024-11-11T01:27:25.559+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='modeling_pipeline' AIRFLOW_CTX_TASK_ID='XGBoost_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T01:27:11.105048+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T01:27:11.105048+00:00'
[2024-11-11T01:27:25.560+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T01:27:25.591+0000] {logging_mixin.py:188} INFO - Data loaded from /opt/***/dags/DataPreprocessing/src/data_store_pkl_files/test_data/no_anamoly_test_data.pkl.
[2024-11-11T01:27:25.593+0000] {logging_mixin.py:188} INFO - Original Skewness: 0.5082849280995185
[2024-11-11T01:27:25.595+0000] {logging_mixin.py:188} INFO - Log Transformed Skewness: -0.38788987353405835
[2024-11-11T01:27:25.604+0000] {logging_mixin.py:188} INFO - Box-Cox Transformed Skewness: 0.011851083745351043
[2024-11-11T01:27:25.606+0000] {logging_mixin.py:188} INFO - Choosing Box-Cox transformed column.
[2024-11-11T01:27:25.613+0000] {logging_mixin.py:188} INFO - Feature engineering completed and NaN values dropped.
[2024-11-11T01:27:25.647+0000] {logging_mixin.py:188} WARNING - 2024/11/11 01:27:25 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-11-11T01:27:27.567+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/mlflow/types/utils.py:407: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(

[2024-11-11T01:27:29.620+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:   0%|          | 0/7 [00:00<?, ?it/s]
[2024-11-11T01:27:29.621+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  14%|#4        | 1/7 [00:00<00:00, 4728.64it/s]
[2024-11-11T01:27:29.621+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  29%|##8       | 2/7 [00:00<00:00, 4417.38it/s]
[2024-11-11T01:27:29.622+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  43%|####2     | 3/7 [00:00<00:00, 4612.50it/s]
[2024-11-11T01:27:29.622+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  57%|#####7    | 4/7 [00:00<00:00, 4562.75it/s]
[2024-11-11T01:27:29.622+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  71%|#######1  | 5/7 [00:00<00:00, 4615.21it/s]
[2024-11-11T01:27:29.622+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  86%|########5 | 6/7 [00:00<00:00, 4849.84it/s]
[2024-11-11T01:27:29.622+0000] {logging_mixin.py:188} WARNING - Downloading artifacts: 100%|##########| 7/7 [00:00<00:00, 5016.25it/s]
[2024-11-11T01:27:29.623+0000] {logging_mixin.py:188} WARNING - Downloading artifacts: 100%|##########| 7/7 [00:00<00:00, 4386.04it/s]
[2024-11-11T01:27:29.718+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

[2024-11-11T01:27:29.721+0000] {logging_mixin.py:188} INFO - RMSE (Box-Cox transformed target): 0.20470293295156336
[2024-11-11T01:27:29.722+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

[2024-11-11T01:27:29.725+0000] {logging_mixin.py:188} INFO - RMSE (Original PM2.5 target): 1.1686009561689805
[2024-11-11T01:27:29.728+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/core.py:158: UserWarning: [01:27:29] WARNING: /workspace/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  warnings.warn(smsg, UserWarning)

[2024-11-11T01:27:29.730+0000] {logging_mixin.py:188} INFO - Model saved at /opt/***/dags/weights/xgboost_pm25_model.pth
[2024-11-11T01:27:29.734+0000] {logging_mixin.py:188} INFO - Model loaded from /opt/***/dags/weights/xgboost_pm25_model.pth
[2024-11-11T01:27:29.782+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T01:27:29.784+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ModelDevelopment/XGBoost.py", line 143, in main
    xgb_model.plot_results(y_pred_original)
  File "/opt/airflow/dags/ModelDevelopment/XGBoost.py", line 97, in plot_results
    mlflow.log_artifact(plot_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 1130, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 1928, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 841, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 45, in log_artifact
    shutil.copy2(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/usr/local/lib/python3.12/shutil.py", line 475, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/artifacts/pm25_actual_vs_predicted_XGBoost.png'
[2024-11-11T01:27:29.831+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=modeling_pipeline, task_id=XGBoost_model, run_id=manual__2024-11-11T01:27:11.105048+00:00, execution_date=20241111T012711, start_date=20241111T012725, end_date=20241111T012729
[2024-11-11T01:27:29.858+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 818 for task XGBoost_model ([Errno 2] No such file or directory: '/opt/airflow/dags/artifacts/pm25_actual_vs_predicted_XGBoost.png'; 139)
[2024-11-11T01:27:29.949+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-11T01:27:29.964+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
