[2024-11-14T04:03:53.903+0000] {processor.py:161} INFO - Started process (PID=31583) to work on /opt/airflow/dags/gcs_file_pipeline_dag.py
[2024-11-14T04:03:53.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/gcs_file_pipeline_dag.py for tasks to queue
[2024-11-14T04:03:53.906+0000] {logging_mixin.py:188} INFO - [2024-11-14T04:03:53.906+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_file_pipeline_dag.py
[2024-11-14T04:03:54.480+0000] {logging_mixin.py:188} INFO - [2024-11-14T04:03:54.478+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/gcs_file_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_file_pipeline_dag.py", line 215, in <module>
    from my_operators.data_air import download_data_function
ModuleNotFoundError: No module named 'my_operators'
[2024-11-14T04:03:54.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_file_pipeline_dag.py
[2024-11-14T04:03:54.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/gcs_file_pipeline_dag.py took 0.595 seconds
