[2024-11-03T02:38:20.248+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-03T02:38:20.265+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_missing_vals_test manual__2024-11-03T02:36:44.429080+00:00 [queued]>
[2024-11-03T02:38:20.361+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_missing_vals_test manual__2024-11-03T02:36:44.429080+00:00 [queued]>
[2024-11-03T02:38:20.362+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-03T02:38:20.374+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_anomalies_missing_vals_test> on 2024-11-03 02:36:44.429080+00:00
[2024-11-03T02:38:20.382+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=368) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T02:38:20.384+0000] {standard_task_runner.py:63} INFO - Started process 377 to run task
[2024-11-03T02:38:20.384+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'check_anomalies_missing_vals_test', 'manual__2024-11-03T02:36:44.429080+00:00', '--job-id', '732', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmp8uoadwa4']
[2024-11-03T02:38:20.386+0000] {standard_task_runner.py:91} INFO - Job 732: Subtask check_anomalies_missing_vals_test
[2024-11-03T02:38:20.427+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.check_anomalies_missing_vals_test manual__2024-11-03T02:36:44.429080+00:00 [running]> on host 7ffb0854de89
[2024-11-03T02:38:20.470+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='check_anomalies_missing_vals_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T02:36:44.429080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T02:36:44.429080+00:00'
[2024-11-03T02:38:20.471+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-03T02:38:20.479+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-03T02:38:20.483+0000] {dag_script.py:110} INFO - Anomalies detected: ['Total missing values: 2317']
[2024-11-03T02:38:20.484+0000] {dag_script.py:112} INFO - send_anomaly_alert_handle_missing_vals_test
[2024-11-03T02:38:20.484+0000] {python.py:237} INFO - Done. Returned value was: send_anomaly_alert_handle_missing_vals_test
[2024-11-03T02:38:20.484+0000] {branch.py:36} INFO - Branch into send_anomaly_alert_handle_missing_vals_test
[2024-11-03T02:38:20.484+0000] {skipmixin.py:178} INFO - Following branch send_anomaly_alert_handle_missing_vals_test
[2024-11-03T02:38:20.496+0000] {skipmixin.py:246} INFO - Skipping tasks [('continue_pipeline_handle_missing_vals_test', -1)]
[2024-11-03T02:38:20.504+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-03T02:38:20.511+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=check_anomalies_missing_vals_test, run_id=manual__2024-11-03T02:36:44.429080+00:00, execution_date=20241103T023644, start_date=20241103T023820, end_date=20241103T023820
[2024-11-03T02:38:20.528+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-03T02:38:20.545+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-03T02:38:20.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
