[2024-11-05T01:22:58.157+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T01:22:58.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_split_data manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:22:58.245+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_split_data manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:22:58.245+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-05T01:22:58.250+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_anomalies_split_data> on 2024-11-05 01:22:21.867548+00:00
[2024-11-05T01:22:58.255+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T01:22:58.256+0000] {standard_task_runner.py:63} INFO - Started process 227 to run task
[2024-11-05T01:22:58.257+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'check_anomalies_split_data', 'manual__2024-11-05T01:22:21.867548+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmpp4t1pgjg']
[2024-11-05T01:22:58.258+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask check_anomalies_split_data
[2024-11-05T01:22:58.276+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.check_anomalies_split_data manual__2024-11-05T01:22:21.867548+00:00 [running]> on host b260d3fe343d
[2024-11-05T01:22:58.313+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='check_anomalies_split_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T01:22:21.867548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T01:22:21.867548+00:00'
[2024-11-05T01:22:58.314+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T01:22:58.320+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-05T01:22:58.325+0000] {dag_script.py:56} INFO - Anomalies detected: []
[2024-11-05T01:22:58.325+0000] {dag_script.py:60} INFO - Branching to continue_pipeline
[2024-11-05T01:22:58.325+0000] {python.py:237} INFO - Done. Returned value was: continue_pipeline_train_test
[2024-11-05T01:22:58.325+0000] {branch.py:36} INFO - Branch into continue_pipeline_train_test
[2024-11-05T01:22:58.325+0000] {skipmixin.py:178} INFO - Following branch continue_pipeline_train_test
[2024-11-05T01:22:58.331+0000] {skipmixin.py:246} INFO - Skipping tasks [('send_anomaly_alert_train_test', -1)]
[2024-11-05T01:22:58.338+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T01:22:58.344+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=check_anomalies_split_data, run_id=manual__2024-11-05T01:22:21.867548+00:00, execution_date=20241105T012221, start_date=20241105T012258, end_date=20241105T012258
[2024-11-05T01:22:58.354+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-05T01:22:58.374+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T01:22:58.374+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
