[2024-11-05T01:23:11.209+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T01:23:11.301+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_removal_data_train manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:23:11.305+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_removal_data_train manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:23:11.306+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-05T01:23:11.310+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_anomalies_removal_data_train> on 2024-11-05 01:22:21.867548+00:00
[2024-11-05T01:23:11.315+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=275) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T01:23:11.316+0000] {standard_task_runner.py:63} INFO - Started process 284 to run task
[2024-11-05T01:23:11.317+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'check_anomalies_removal_data_train', 'manual__2024-11-05T01:22:21.867548+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmpx1hufjby']
[2024-11-05T01:23:11.318+0000] {standard_task_runner.py:91} INFO - Job 153: Subtask check_anomalies_removal_data_train
[2024-11-05T01:23:11.341+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.check_anomalies_removal_data_train manual__2024-11-05T01:22:21.867548+00:00 [running]> on host b260d3fe343d
[2024-11-05T01:23:11.381+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='check_anomalies_removal_data_train' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T01:22:21.867548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T01:22:21.867548+00:00'
[2024-11-05T01:23:11.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T01:23:11.387+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-05T01:23:11.392+0000] {dag_script.py:83} INFO - Anomalies detected: ["None of the columns ['co', 'no', 'no2', 'o3', 'so2'] exist in the DataFrame"]
[2024-11-05T01:23:11.392+0000] {dag_script.py:85} INFO - send_anomaly_alert_remove_cols_train
[2024-11-05T01:23:11.392+0000] {python.py:237} INFO - Done. Returned value was: send_anomaly_alert_remove_cols_train
[2024-11-05T01:23:11.392+0000] {branch.py:36} INFO - Branch into send_anomaly_alert_remove_cols_train
[2024-11-05T01:23:11.392+0000] {skipmixin.py:178} INFO - Following branch send_anomaly_alert_remove_cols_train
[2024-11-05T01:23:11.398+0000] {skipmixin.py:246} INFO - Skipping tasks [('continue_pipeline_remove_cols_train', -1)]
[2024-11-05T01:23:11.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T01:23:11.413+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=check_anomalies_removal_data_train, run_id=manual__2024-11-05T01:22:21.867548+00:00, execution_date=20241105T012221, start_date=20241105T012311, end_date=20241105T012311
[2024-11-05T01:23:11.461+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-05T01:23:11.497+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T01:23:11.498+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
