[2024-11-12T03:18:32.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T03:18:32.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_pipeline.Prophet_model_validation manual__2024-11-12T03:17:14.034180+00:00 [queued]>
[2024-11-12T03:18:32.533+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_pipeline.Prophet_model_validation manual__2024-11-12T03:17:14.034180+00:00 [queued]>
[2024-11-12T03:18:32.533+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-12T03:18:32.540+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Prophet_model_validation> on 2024-11-12 03:17:14.034180+00:00
[2024-11-12T03:18:32.554+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=198) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T03:18:32.555+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2024-11-12T03:18:32.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'modeling_pipeline', 'Prophet_model_validation', 'manual__2024-11-12T03:17:14.034180+00:00', '--job-id', '1020', '--raw', '--subdir', 'DAGS_FOLDER/dag_script_model.py', '--cfg-path', '/tmp/tmpi5vut92p']
[2024-11-12T03:18:32.558+0000] {standard_task_runner.py:91} INFO - Job 1020: Subtask Prophet_model_validation
[2024-11-12T03:18:32.602+0000] {task_command.py:426} INFO - Running <TaskInstance: modeling_pipeline.Prophet_model_validation manual__2024-11-12T03:17:14.034180+00:00 [running]> on host 5039cd089413
[2024-11-12T03:18:32.651+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='modeling_pipeline' AIRFLOW_CTX_TASK_ID='Prophet_model_validation' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T03:17:14.034180+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T03:17:14.034180+00:00'
[2024-11-12T03:18:32.652+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T03:18:32.667+0000] {logging_mixin.py:188} INFO - /opt/***
[2024-11-12T03:18:32.678+0000] {logging_mixin.py:188} INFO - Data loaded from /opt/***/dags/DataPreprocessing/src/data_store_pkl_files/test_data/no_anamoly_test_data.pkl.
[2024-11-12T03:18:32.680+0000] {logging_mixin.py:188} INFO - Original Skewness: 0.5082849280995185
[2024-11-12T03:18:32.682+0000] {logging_mixin.py:188} INFO - Log Transformed Skewness: -0.38788987353405835
[2024-11-12T03:18:32.691+0000] {logging_mixin.py:188} INFO - Box-Cox Transformed Skewness: 0.011851083745351043
[2024-11-12T03:18:32.692+0000] {logging_mixin.py:188} INFO - Choosing Box-Cox transformed column.
[2024-11-12T03:18:32.700+0000] {logging_mixin.py:188} INFO - Feature engineering completed and NaN values dropped.
[2024-11-12T03:18:32.750+0000] {logging_mixin.py:188} WARNING - 2024/11/12 03:18:32 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-11-12T03:18:32.797+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T03:18:32.797+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ModelDevelopment/Validation/Prophet.py", line 173, in main
    y_pred_original = prophet_model.evaluate()
                      ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Prophet' object has no attribute 'evaluate'
[2024-11-12T03:18:32.808+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=modeling_pipeline, task_id=Prophet_model_validation, run_id=manual__2024-11-12T03:17:14.034180+00:00, execution_date=20241112T031714, start_date=20241112T031832, end_date=20241112T031832
[2024-11-12T03:18:32.816+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1020 for task Prophet_model_validation ('Prophet' object has no attribute 'evaluate'; 207)
[2024-11-12T03:18:32.862+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T03:18:32.878+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T03:18:32.884+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
